#!/usr/bin/env bash

#
# {{@@ header() @@}}
#

userresources={{@@ env['HOME'] @@}}/.Xresources
usermodmap={{@@ env['HOME'] @@}}/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[[ -f ${sysresources} ]] && xrdb -merge ${sysresources}

[[ -f ${sysmodmap} ]] && xmodmap ${sysmodmap}

[[ -f "${userresources}" ]] && xrdb -merge "${userresources}"

[[ -f "${usermodmap}" ]] && xmodmap "${usermodmap}"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "${f}" ] && . "${f}"
 done
 unset f
fi

# Start gnome keyring deamon
eval $(/u)

# Start gnome keyring daemon
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,gpg)
# Tells dbus to add DISPLAY to its own environment variables
dbus-update-activation-environment --systemd DISPLAY
