#
# {{@@ env['dotdrop_warning'] @@}}
#


# Fix for JetBrains with non-re-parenting window managers
export _JAVA_AWT_WM_NONREPARENTING=1
# Disable Ansible cowsay
export ANSIBLE_NOCOWS=1
# Include ~/.bin to PATH
if [ -d "$HOME/.bin" ] ; then
	export PATH="$HOME/.bin:$PATH"
fi
# Includ ~/.local/bin to PATH
if [ -d "$HOME/.local/bin" ] ; then
	export PATH="$HOME/.local/bin:$PATH"
fi

