#
# {{@@ header() @@}}
#

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-{{@@ env['HOME'] @@}}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-{{@@ env['HOME'] @@}}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f {{@@ env['HOME'] @@}}/.p10k.zsh ]] || source {{@@ env['HOME'] @@}}/.p10k.zsh

# If you come from bash you might have to change your $PATH.
# export PATH=${HOME}/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH={{@@ env['HOME'] @@}}/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
if [[ ${TERM} == 'linux' ]]; then
  ZSH_THEME="agnoster"
else
  ZSH_THEME="powerlevel10k/powerlevel10k"
fi

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Load pyenv-virtualenv when found
ZSH_PYENV_VIRTUALENV="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
{%@@ if profile == 'yoetunheimr' or profile == 'AINCRAD-wsl' or profile == 'AINCRAD' or profile == 'YOETUNHEIMR-wsl' or profile == 'ymir' @@%}  archlinux
{%@@ endif @@%}  aws
  colored-man-pages
  cp
  fzf
  git
  git-extras
  gitignore
  kubectl
  nix-zsh-completions
  pip
  pyenv
  pylint
  python
  screen
  sublime
  sudo
  systemd
  themes
  vscode
  #zsh-completions (https://github.com/zsh-users/zsh-completions/issues/603)
  zsh-navigation-tools
  zsh-ssh
)

autoload -U compinit && compinit

{%@@ if profile == 'ymir' @@%}
# Source fzf-tab-completions
# source {{@@ env['HOME'] @@}}/.oh-my-zsh/custom/plugins/fzf-tab-completion/zsh/fzf-zsh-completion.sh
# zstyle ':completion:*' fzf-search-display true

# fpath extensions
# Add zsh-completions to fpath (https://github.com/zsh-users/zsh-completions/issues/603)
fpath+={{@@ env['HOME'] @@}}/.oh-my-zsh/custom/plugins/zsh-completions/src
# A set of custom completions
fpath+={{@@ env['HOME'] @@}}/.oh-my-zsh/custom/plugins/custom-completions
{%@@ endif @@%}

source ${ZSH}/oh-my-zsh.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# [[ -f {{@@ env['HOME'] @@}}/.files/dotdrop.sh ]] && alias dotdrop='eval $(grep -v "^#" {{@@ env['HOME'] @@}}/.files/.env.public) {{@@ env['HOME'] @@}}/.files/dotdrop.sh' # Not required anymore since I now use
[[ $(command -v thefuck) ]] && eval $(thefuck --alias)
#{%@@ if profile == 'AINCRAD-wsl' or profile == 'YOETUNHEIMR-wsl' or profile == 'ymir' @@%}
# Use https://github.com/jgaa/shinysocks as simple socks5 proxy for windows
#[[ $(command -v kubectl) ]] && alias proxy_kubectl="http_proxy=socks5://$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):1080 https_proxy=socks5://$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):1080 kubectl"
#[[ $(command -v kubectl) ]] && alias pk='proxy_kubectl'
#{%@@ endif @@%}

alias ssh-no-check="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

# exa
if [[ $(command -v exa) ]]; then
        lfunc() {
                exal -T -L ${1:-1}
        }
        lafunc() {
                exal -a -T -L ${1:-1}
        }
        alias exal="exa -l -F -g -h --extended --git --group-directories-first --icons"
        alias l='lfunc'
        alias la='lafunc'
        alias ll="lfunc 2"
        alias lla='lafunc 2'
fi

# Initialize pyenv
[[ $(command -v pyenv) ]] && export PYENV_ROOT="$HOME/.pyenv"
[[ $(command -v pyenv) ]] && command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
[[ $(command -v pyenv) ]] && eval "$(pyenv init -)"

# Enable pipx completions
if [ -f "{{@@ env['HOME'] @@}}/.local/bin/pipx" ]; then
  autoload -U bashcompinit
  bashcompinit
  eval "$(register-python-argcomplete pipx)"
fi

{%@@ if profile == 'WVDEWOBMC001307' @@%}
# Decide which homebrew installation (x64_86 / arm64) should be used
if [ "$(sysctl -n sysctl.proc_translated)" = "1" ]; then
  local brew_path="/usr/local/homebrew/bin"
else
  local brew_path="/opt/homebrew/bin"
fi
export PATH="${brew_path}:${PATH}"
{%@@ endif @@%}

# Functions (or more complex aliases)
wttr() {
    if [ -z "${1}" ]; then
        curl http://wttr.in
    elif [[ "${1}" == "help" ]]; then
        cat << EOF
usage: wttr (City|3-letter airport code|'~Special+Location')
  City:
    Just write down the name of the city.
    e.G.:
      wttr London
  3-letter airport code:
    Use 3-letter airport codes in order to get the weather information at a certain airport.
    e.G.:
      wttr muc #for Munich Internation Airpot, Germany
  Special Location:
    Let's say you'd like to get the weather for a geographical location other than a town or city -
    maybe an attraction in a city, a mountain name, or some special location.
    Add the character '~' before the name to look up that special location name before the weather is then retrieved.
    e.G.:
      wttr '~Eiffel+Tower'
      wttr '~Kilimanjaro'
EOF
    else
        curl http://wttr.in/${1}
    fi
}

{%@@ if profile == 'WVDEWOBMC001307' @@%}
macnst (){
  netstat -Watnlv | grep LISTEN | awk '{"ps -o comm= -p " $9 | getline procname;colred="\033[01;31m";colclr="\033[0m"; print colred "proto: " colclr $1 colred " | addr.port: " colclr $4 colred " | pid: " colclr $9 colred " | name: " colclr procname;  }' | column -t -s "|"
}

function setProxyEnv(){
  local HIGHLIGHT='\033[36;1m'
  local RESET='\033[0;0m'

  local PROXY='127.0.0.1:9000'
  local PROXY_CFG_HTTP="${PROXY}"
  local PROXY_CFG_HTTPS="${PROXY}"
  local NO_PROXY_CFG="127.0.0.1,localhost,vw.vwg"
  
  export NO_PROXY="${NO_PROXY_CFG}"
  export no_proxy="${NO_PROXY_CFG}"
  export HTTP_PROXY="${PROXY_CFG_HTTP}"
  export HTTPS_PROXY="${PROXY_CFG_HTTPS}"
  export http_proxy="${PROXY_CFG_HTTP}"
  export https_proxy="${PROXY_CFG_HTTPS}"

  echo -e "\n✈️  exported zscaler proxy: ${HIGHLIGHT}http://${PROXY}${RESET}"
}

function unsetProxyEnv(){
  unset NO_PROXY
  unset HTTP_PROXY
  unset HTTPS_PROXY
  unset no_proxy
  unset http_proxy
  unset https_proxy

  echo -e "\n🔄 removed zscaler proxy cofiguration"
}

function setVpnGitRemote(){
  local ORIGIN=vpn #e.g.
  local HIGHLIGHT='\033[36;1m'
  local RESET='\033[0;0m'

  local repo="ssh://git@vpn.github.com:443/${$(git config remote.origin.url)#*git@github.com:}"
  git remote add ${ORIGIN} "${repo}" 2> /dev/null

  echo -e "🔗 git remote (${HIGHLIGHT}${ORIGIN}${RESET}): ${HIGHLIGHT}${repo}${RESET}\n"
}
{%@@ endif @@%}

{%@@ if profile == 'ymir' @@%}
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc
{%@@ endif @@%}
